name: coverage

on:
  pull_request:
    branches:
      - master
      - main
      - Jest

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
  push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Jest'
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
